// lib/emailService.ts
import nodemailer from 'nodemailer';

interface EmailConfig {
  host: string;
  port: number;
  secure?: boolean;
  auth: {
    user: string;
    pass: string;
  };
}

interface IssueEmailData {
  title: string;
  description: string;
  userAgent: string;
  timestamp: string;
  to: string;
  from: string;
}

/**
 * Creates a nodemailer transporter with the provided configuration
 */
function createTransporter(config: EmailConfig) {
  return nodemailer.createTransport({
    host: config.host,
    port: config.port,
    secure: config.secure || false, // true for 465, false for other ports
    auth: {
      user: config.auth.user,
      pass: config.auth.pass,
    },
  });
}

/**
 * Sends an issue report via email as a fallback when GitHub integration is not available
 */
export async function sendIssueEmail(data: IssueEmailData): Promise<boolean> {
  try {
    const config: EmailConfig = {
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: parseInt(process.env.SMTP_PORT || '587', 10),
      secure: process.env.SMTP_PORT === '465',
      auth: {
        user: process.env.SMTP_USER || '',
        pass: process.env.SMTP_PASSWORD || '',
      },
    };

    // Validate email configuration
    if (!config.auth.user || !config.auth.pass) {
      console.error('Email configuration is incomplete');
      return false;
    }

    const transporter = createTransporter(config);

    // Email content
    const mailOptions = {
      from: data.from,
      to: data.to,
      subject: `[GaengleSimulator] Issue Report: ${data.title}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #dc2626;">Issue Report - GaengleSimulator</h2>
          
          <div style="background-color: #f3f4f6; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <h3 style="margin-top: 0; color: #374151;">Title:</h3>
            <p style="margin-bottom: 0;">${data.title}</p>
          </div>
          
          <div style="background-color: #f3f4f6; padding: 15px; border-radius: 5px; margin: 20px 0;">
            <h3 style="margin-top: 0; color: #374151;">Description:</h3>
            <p style="white-space: pre-wrap; margin-bottom: 0;">${data.description}</p>
          </div>
          
          <div style="background-color: #fef3c7; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #f59e0b;">
            <h3 style="margin-top: 0; color: #92400e;">Technical Details:</h3>
            <p style="margin: 5px 0;"><strong>Timestamp:</strong> ${data.timestamp}</p>
            <p style="margin: 5px 0;"><strong>User Agent:</strong> ${data.userAgent}</p>
            <p style="margin: 5px 0;"><strong>Reported via:</strong> App Issue Reporter (Email Fallback)</p>
          </div>
          
          <div style="margin-top: 30px; padding: 15px; background-color: #eff6ff; border-radius: 5px; border-left: 4px solid #3b82f6;">
            <p style="margin: 0; color: #1e40af;">
              <strong>Note:</strong> This issue was sent via email because GitHub integration is not configured. 
              To enable direct GitHub issue creation, please configure the GITHUB_TOKEN environment variable.
            </p>
          </div>
          
          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px;">
            <p>This email was automatically generated by the GaengleSimulator Issue Reporter.</p>
            <p>Repository: <a href="https://github.com/tinur5/GaengleSimulator">tinur5/GaengleSimulator</a></p>
          </div>
        </div>
      `,
    };

    // Send email
    const info = await transporter.sendMail(mailOptions);
    console.log('Email sent successfully:', info.messageId);
    return true;
  } catch (error) {
    console.error('Error sending email:', error);
    return false;
  }
}
